server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    # 在 Feign 中开启 Hystrix
    enabled: true

logging:
  level:
    # 配置 service 包下的 client 的日志打印级别为 debug
    com.example.feignservice.service: debug