server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        # 开启查看路由的端点
        include: 'routes'

hystrix:
  # 用于控制HystrixCommand的行为
  command:
    default:
      execution:
        isolation:
          thread:
            # 配置 HystrixCommand 执行的超时时间，执行超过该时间会进行服务降级处理
            timeoutInMilliseconds: 1000

# 全局配置
ribbon:
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 3000
  # 最大自动重试次数
  MaxAutoRetries: 0
  # 最大自动重试次数下一个服务的次数
  MaxAutoRetriesNextServer: 0


zuul:
  # 给网关路由添加前缀
  prefix: /proxy
  # 关闭默认路由配置
  # ignored-services: user-service,feign-service
  # 配置过滤敏感的请求头信息，设置为空就不会过滤
  sensitive-headers: Cookie,Set-Cookie,Authorization
  # 设置为 true 表示重定向会添加 host 请求头
  add-host-header: true
  PreLogFilter:
    pre:
      disable: true
  # 给服务配置路由
  routes:
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**