server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      # 注册到另一个 Eureka 注册中心
      defaultZone: http://replica1:8002/eureka/
    fetch-registry: true
    register-with-eureka: true

# 由于 defaultZone 使用了域名，所以还需在本机的 host 文件中配置：
# 127.0.0.1 replica1
# 127.0.0.1 replica2